workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.onewrapp.mobile
      xcode: latest
      node: 18
      vars:
        BUNDLE_ID: "com.onewrapp.mobile"
        APP_STORE_APP_ID: "6736345514"
        VITE_URL_PATH_LOCAL: "https://stgapi.onewrapp.com/ow_offline"
        VITE_URL_PATH_STAGING: "https://stgapi.onewrapp.com/ow_offline"
        VITE_URL_PATH_PRODUCTION: "https://api.onewrapp.com/ow_offline"
        VITE_SCENES_ENDPOINT_PULL: "app_scenes_list"
        VITE_SCENE_PARAGRAPHS_ENDPOINT_PULL: "app_scenes_paragraphs"
        VITE_SCENES_ENDPOINT_PUSH: "app_scenes_push"
        VITE_SCENE_PARAGRAPHS_ENDPOINT_PUSH: "app_scenes_paragraphs_push"
        VITE_CLIENT_ID: "195018623531-mm7krht1hr7tj3501el59mug4rj62u5u.apps.googleusercontent.com"
        VITE_CLIENT_ID_ANDROID: "195018623531-2uupgtedp36aiucvc1pnf3hbc9btb2e0.apps.googleusercontent.com"
        VITE_PROJECTS_ENDPOINT_PULL: "app_projects_list"
        VITE_SHOOTINGS_ENDPOINT_PULL: "app_shootings_list"
        VITE_SHOOTINGS_ENDPOINT_PUSH: "app_shootings_push"
        VITE_UNITS_ENDPOINT_PULL: "app_units_list"
        VITE_UNITS_ENDPOINT_PUSH: "app_units_push"
        VITE_TALENTS_ENDPOINT_PULL: "app_talents_list"
        VITE_TALENTS_ENDPOINT_PUSH: "app_talents_push"
        VITE_MAPS_KEY: "AIzaSyA9rz3ykn0BboO4tjO2_fSKE82_CiIZmJI"
        VITE_CREW_ENDPOINT_PULL: "app_crew_list"
        VITE_CREW_ENDPOINT_PUSH: "app_crew_push"
        VITE_COUNTRIES_ENDPOINT_PULL: "app_countries_list"
        VITE_SERVICE_MATRICES_ENDPOINT_PULL: "app_service_matrices_list"
        VITE_SERVICE_MATRICES_ENDPOINT_PUSH: "app_service_matrices_push"
        VITE_USER_ENDPOINT_PULL: "app_user_info"
        VITE_PROJ_WEEKS_ENDPOINT_PULL: "app_proj_weeks_list"
        VITE_STRIPBOARD_ENDPOINT_PULL: "app_stripboards_list"
        VITE_STRIPBOARD_ENDPOINT_PUSH: "app_stripboards_push"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
