require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorGoogleMaps', :path => '../../node_modules/@capacitor/google-maps'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CodetrixStudioCapacitorGoogleAuth', :path => '../../node_modules/@codetrix-studio/capacitor-google-auth'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  require 'fileutils'

  privacy_manifest = <<~XML
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
      <key>NSPrivacyTracking</key><false/>
      <key>NSPrivacyTrackingDomains</key><array/>
      <key>NSPrivacyCollectedDataTypes</key><array/>
      <key>NSPrivacyAccessedAPITypes</key>
      <array>
        <dict>
          <key>NSPrivacyAccessedAPIType</key><string>NSPrivacyAccessedAPICategoryUserDefaults</string>
          <key>NSPrivacyAccessedAPITypeReasons</key><array><string>CA92.1</string></array>
        </dict>
        <dict>
          <key>NSPrivacyAccessedAPIType</key><string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
          <key>NSPrivacyAccessedAPITypeReasons</key><array><string>C617.1</string></array>
        </dict>
        <dict>
          <key>NSPrivacyAccessedAPIType</key><string>NSPrivacyAccessedAPICategorySystemBootTime</string>
          <key>NSPrivacyAccessedAPITypeReasons</key><array><string>35F9.1</string></array>
        </dict>
        <dict>
          <key>NSPrivacyAccessedAPIType</key><string>NSPrivacyAccessedAPICategoryDiskSpace</string>
          <key>NSPrivacyAccessedAPITypeReasons</key><array><string>E174.1</string></array>
        </dict>
      </array>
    </dict>
    </plist>
  XML

  pods_root = installer.sandbox.root.to_s
  node_modules = File.expand_path('../../../node_modules/@capacitor/ios', pods_root)

  sdk_dirs = {
    'Capacitor'        => File.join(node_modules, 'Capacitor', 'Capacitor'),
    'CapacitorCordova' => File.join(node_modules, 'CapacitorCordova', 'CapacitorCordova'),
    'GoogleSignIn'     => File.join(pods_root, 'GoogleSignIn', 'GoogleSignIn'),
    'GTMAppAuth'       => File.join(pods_root, 'GTMAppAuth', 'GTMAppAuth'),
    'GTMSessionFetcher' => File.join(pods_root, 'GTMSessionFetcher', 'Sources'),
  }

  installer.pods_project.targets.each do |target|
    next unless sdk_dirs.key?(target.name)

    dir = sdk_dirs[target.name]
    FileUtils.mkdir_p(dir)
    privacy_path = File.join(dir, 'PrivacyInfo.xcprivacy')
    File.write(privacy_path, privacy_manifest) unless File.exist?(privacy_path)

    next if target.resources_build_phase.files.any? { |f| f.file_ref&.path&.include?('PrivacyInfo.xcprivacy') }

    group = installer.pods_project.main_group.find_subpath(File.join('Pods', target.name), true)
    if group
      file_ref = group.new_file(privacy_path)
      target.resources_build_phase.add_file_reference(file_ref)
    end
  end

  installer.pods_project.save
end
